### ISSUE TITLE
Bad environmental score

### ISSUE THREAD

**Issue by mluberry** [aaronmccall/cvss#2]
Hi,

It seems that the environmental score is inaccurate for this vector : 
CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:H/E:H/RL:U/RC:C/CR:H/IR:H/AR:H/MAV:N/MAC:L/MPR:N/MUI:N/MS:C/MC:H/MI:H/MA:H

We have a value of 9.7 instead of 10.0.

Is it possible to fix this ?
Thanks for your job.

Matt

**Comment by aaronmccall** [comment]
@mluberry, I will look into the cause of this issue. Thanks for letting me know.

**Comment by aaronmccall** [comment]
Version 1.0.3 published with fix.

**Comment by mluberry** [comment]
@aaronmccall Thank your for the fix
