### ISSUE TITLE
Environmental Options

### ISSUE THREAD

**Issue by thxmike** [aaronmccall/cvss#6]
In your options, you specify in your documentation, you have an option for environmental in getScore
https://github.com/aaronmccall/cvss
options.environment

However, in reviewing the code, it appears you are looking for an options called env and not environmental. 

This should be corrected.

**Comment by aaronmccall** [comment]
Thank you for bringing this to my attention, @thxmike. I'll get it fixed soon.

**Comment by aaronmccall** [comment]
Version 1.0.5 is published to npm.
